ClientsCRUD/ClientsCRUD/Models/Clients.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ClientsCRUD.Models
{
	public class Clients
	{
		[Key]
		public int Id { get; set; }

		[Required]
		public string FirstName { get; set; } = "";

        [Required]
        public string LastName { get; set; } = "";

        [Required]
        public string PhoneNumber { get; set; } = "";

        public string Email { get; set; } = ""; 
    }
}

ClientsCRUD/ClientsCRUD/Models/ErrorViewModel.cs
namespace ClientsCRUD.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ClientsCRUD/ClientsCRUD/Controllers/ClientsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using ClientsCRUD.Data;
using ClientsCRUD.Models;

namespace ClientsCRUD.Controllers
{
	public class ClientsController : Controller
	{
		private readonly ApplicationDbContext _db;

		public ClientsController(ApplicationDbContext  context)
		{
			_db = context;
		}

		// GET Controller
		public IActionResult Index()
		{
			List<Clients> clients = _db.clients.ToList();
			return View(clients);
		}

		// GET: Create
		public IActionResult Create()
		{
			return View();
		}

		// POST : Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Clients obj)
		{
			if(ModelState.IsValid)
			{
				_db.Add(obj);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
            return View(obj);
        }

        // GET: Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.clients.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

		// POST : Delete
		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost	(int? id)
		{
            var obj = _db.clients.Find(id);
            if (obj == null)
				return NotFound();

            _db.clients.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

		// GET : Edit

		public IActionResult Edit(int? id)
		{
			if ((id == null) || (id == 0))
				return NotFound();

			var obj = _db.clients.Find(id);

			if (obj == null)
				return NotFound();

			return View(obj);

		}
    }
}

ClientsCRUD/ClientsCRUD/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ClientsCRUD.Models;

namespace ClientsCRUD.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ClientsCRUD/ClientsCRUD/Views/Clients/Create.cshtml
@model ClientsCRUD.Models.Clients

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PhoneNumber"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Email"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn  btn-success w-100"><i class="fa-solid fa-rotate-left"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ClientsCRUD/ClientsCRUD/Views/Clients/Delete.cshtml
@model ClientsCRUD.Models.Clients

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Client</h2>
        </div>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" disabled class="form-control" />
                    </div>


                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="PhoneNumber"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="PhoneNumber" disabled class="form-control" />
                        </div>

                        <div class="form-group row">
                            <div class="col-4">
                                <label asp-for="Email"></label>
                            </div>
                            <div class="col-8">
                                <input asp-for="Email" disabled class="form-control" />
                            </div>

                            <div class="form-group row">
                                <div class="col-8 offset-4 row">

                                    <div class="col">
                                        <input type="submit" class="btn btn-danger w-100" value="Delete" />
                                    </div>
                                    <div class="col">
                                        <a asp-action="Index" class="btn  btn-success w-100"><i class="fa-solid fa-rotate-left"></i>Back</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ClientsCRUD/ClientsCRUD/Views/Clients/Index.cshtml
@model IEnumerable<ClientsCRUD.Models.Clients>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Clients List</h2>
        </div>

        <div class="col-6 text-right">
            <a asp-controller="Clients" asp-action="Create" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i> &nbsp; Create New Client

            </a>
        </div>
    </div>


    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                    <th>
                        Phone Number
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        For CRUD
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="10%">@obj.Id</td>
                        <td width="20%">@obj.FirstName</td>
                        <td width="20%">@obj.LastName</td>
                        <td width="20%">@obj.PhoneNumber</td>
                        <td width="30%">@obj.Email</td>

                        <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Clients" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <a asp-controller="Clients" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                <i class="fa-solid fa-trash-can"></i>
                            </a>
                        </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No clients exits.</p>
    }

ClientsCRUD/ClientsCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClientsCRUD/ClientsCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientsCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClientsCRUD.styles.css" asp-append-version="true" />
    <lint rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClientsCRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ClientsCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://kit.fontawesome.com/0d7ba0a743.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>